Zadanie 2: Máte na vstupe nasledujúce dáta, ktoré reprezentujú celočíselné sekvencie s prvkami 0-9:

sequences = [[1, 2, 3, 1, 4, 5], [7, 8, 9, 2, 1, 4, 5], [7, 8, 9, 2, 1, 4]]

1. Vytvorte maticu embeddings, ktorá bude mať rozmer 10x5 inicializovanú náhodne s hodnotami v rozsahu [0,1)
2. Pre každý zoznam s zo zoznamu sequences vytvorte maticu v s rozmerom dĺžka s x 5, pre ktorú platí v[i] = embeddings[s[i]] (tzn. riadok matice v je nastavený na riadok matice embeddings podľa indexu, ktorý je prvkom na danej pozícii v zozname s)
3. Rozšírte matice v tak aby každá mala rovnaký rozmer podľa maximálnej dĺžky zoznamu doplnením 0 hodnôt a spojte ich do výslednej matice data o rozmeroch počet sekvencií x max. dĺžka sekvencie x 5

In [2]:
import numpy as np
sequences = [[1, 2, 3, 1, 4, 5], [7, 8, 9, 2, 1, 4, 5], [7, 8, 9, 2, 1, 4]]

In [6]:
embeddings = np.random.random((10,5))
embeddings.shape

(10, 5)

In [7]:
embeddings

array([[0.58684694, 0.36274049, 0.36068917, 0.1698424 , 0.02635723],
       [0.67118467, 0.32132646, 0.96115908, 0.44998791, 0.25303512],
       [0.10064088, 0.71325968, 0.45620607, 0.05991944, 0.14835948],
       [0.27429414, 0.19355404, 0.98856368, 0.63096783, 0.71663361],
       [0.96896917, 0.79059964, 0.19356001, 0.98386487, 0.35446411],
       [0.75665809, 0.82766994, 0.04090273, 0.91397077, 0.73834738],
       [0.00303868, 0.33946425, 0.3930195 , 0.94935478, 0.9952686 ],
       [0.07279867, 0.2842785 , 0.59972421, 0.12590734, 0.62402327],
       [0.38817433, 0.01177728, 0.69205907, 0.09669856, 0.7076793 ],
       [0.09833716, 0.57121624, 0.36738955, 0.20112286, 0.00980309]])

In [23]:
matice = []
max_dlzka = 0
for zoznam in sequences:
    max_dlzka = max(max_dlzka, len(zoznam))
    matica = embeddings[zoznam]
    matice.append(matica)

In [16]:
matice

[array([[0.67118467, 0.32132646, 0.96115908, 0.44998791, 0.25303512],
        [0.10064088, 0.71325968, 0.45620607, 0.05991944, 0.14835948],
        [0.27429414, 0.19355404, 0.98856368, 0.63096783, 0.71663361],
        [0.67118467, 0.32132646, 0.96115908, 0.44998791, 0.25303512],
        [0.96896917, 0.79059964, 0.19356001, 0.98386487, 0.35446411],
        [0.75665809, 0.82766994, 0.04090273, 0.91397077, 0.73834738]]),
 array([[0.07279867, 0.2842785 , 0.59972421, 0.12590734, 0.62402327],
        [0.38817433, 0.01177728, 0.69205907, 0.09669856, 0.7076793 ],
        [0.09833716, 0.57121624, 0.36738955, 0.20112286, 0.00980309],
        [0.10064088, 0.71325968, 0.45620607, 0.05991944, 0.14835948],
        [0.67118467, 0.32132646, 0.96115908, 0.44998791, 0.25303512],
        [0.96896917, 0.79059964, 0.19356001, 0.98386487, 0.35446411],
        [0.75665809, 0.82766994, 0.04090273, 0.91397077, 0.73834738]]),
 array([[0.07279867, 0.2842785 , 0.59972421, 0.12590734, 0.62402327],
        [0.38817

In [18]:
matice[0].shape

(6, 5)

In [19]:
matice[1].shape

(7, 5)

In [20]:
matice[2].shape

(6, 5)

In [24]:
max_dlzka

7

In [26]:
rozsirene_matice = []
for matica in matice:
    dlzka = matica.shape[0]
    rozdiel = max_dlzka - dlzka
    if rozdiel > 0:
        pridaj = np.zeros((rozdiel, matica.shape[1]))
        matica = np.vstack([matica, pridaj])
    rozsirene_matice.append(matica)

In [27]:
rozsirene_matice

[array([[0.67118467, 0.32132646, 0.96115908, 0.44998791, 0.25303512],
        [0.10064088, 0.71325968, 0.45620607, 0.05991944, 0.14835948],
        [0.27429414, 0.19355404, 0.98856368, 0.63096783, 0.71663361],
        [0.67118467, 0.32132646, 0.96115908, 0.44998791, 0.25303512],
        [0.96896917, 0.79059964, 0.19356001, 0.98386487, 0.35446411],
        [0.75665809, 0.82766994, 0.04090273, 0.91397077, 0.73834738],
        [0.        , 0.        , 0.        , 0.        , 0.        ]]),
 array([[0.07279867, 0.2842785 , 0.59972421, 0.12590734, 0.62402327],
        [0.38817433, 0.01177728, 0.69205907, 0.09669856, 0.7076793 ],
        [0.09833716, 0.57121624, 0.36738955, 0.20112286, 0.00980309],
        [0.10064088, 0.71325968, 0.45620607, 0.05991944, 0.14835948],
        [0.67118467, 0.32132646, 0.96115908, 0.44998791, 0.25303512],
        [0.96896917, 0.79059964, 0.19356001, 0.98386487, 0.35446411],
        [0.75665809, 0.82766994, 0.04090273, 0.91397077, 0.73834738]]),
 array([[0.07279

In [28]:
rozsirene_matice[0].shape

(7, 5)

In [29]:
data = np.array(rozsirene_matice)

In [30]:
data.shape

(3, 7, 5)